FROM python:3.8-slim

WORKDIR /app

COPY app.py requirements.api.txt ./
COPY consumer.py requirements.consumer.txt ./

RUN pip install --no-cache-dir -r requirements.api.txt
RUN pip install --no-cache-dir -r requirements.consumer.txt

CMD ["python", "app.py"]
